# OpenAPI/Swagger Configuration
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.enable=true
quarkus.smallrye-openapi.info-title=PTSS SUPPORT API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=This is the ptss support api

# Server Configuration
quarkus.http.port=8080
%dev.quarkus.live-reload.instrumentation=true
# Disable Quarkus built-in authentication
quarkus.http.auth=none
quarkus.security.enabled=false
quarkus.smallrye-jwt.enabled=false
quarkus.health.openapi.included=true

# OpenShift Configuration
quarkus.openshift.deployment-kind=Deployment
quarkus.kubernetes-client.trust-certs=true
quarkus.openshift.expose=true
quarkus.openshift.namespace=hotel-dev
quarkus.openshift.build-strategy=docker

# Container Image Configuration
quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000
quarkus.container-image.builder=openshift
quarkus.container-image.group=hotel-dev
quarkus.container-image.name=user-service
quarkus.container-image.tag=1.0-SNAPSHOT
quarkus.application.name=user-service

# Resource Configuration
quarkus.openshift.resources.requests.memory=512Mi
quarkus.openshift.resources.requests.cpu=250m
quarkus.openshift.resources.limits.memory=1Gi
quarkus.openshift.resources.limits.cpu=500m

# Prometheus Configuration
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics

# Hibernate configurations
# Switch from `update` to `drop-and-create` if large changes were made (data will be lost)
#%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.database.generation=update
%test.quarkus.hibernate-orm.database.generation=drop-and-create
# Switch from `validate` to `drop-and-create` if large changes were made or first deployment (data will be lost)
# or `update` if basic table changes were made
#%prod.quarkus.hibernate-orm.database.generation=drop-and-create
# Use this if the ORM/repository changes are final
%prod.quarkus.hibernate-orm.database.generation=validate
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.hibernate-orm.database.generation.create-schemas=true

# PostgreSQL Configuration for Quarkus
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.default-schema=${POSTGRESQL_DB_SCHEMA:user_service}
quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRESQL_DB_HOST:localhost}:5432/${POSTGRESQL_DB_NAME:dev_database}?currentSchema=${POSTGRESQL_DB_SCHEMA:user_service}
quarkus.datasource.username=${POSTGRESQL_DB_USERNAME:postgres}
quarkus.datasource.password=${POSTGRESQL_DB_PASSWORD:postgres}

# User-service-related Configuration
app.invitation.validity.hours=48
app.forgot_password.validity.minutes=15

# Mailing properties
quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
quarkus.mailer.from=${GMAIL_ADDRESS}
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=${GMAIL_ADDRESS}
quarkus.mailer.password=${GMAIL_APP_PASSWORD}
quarkus.mailer.mock=false